blank_issues_enabled: false
contact_links:
  - name: Report a Bug
    url: https://github.com/SteveLLamb/mediastandards-registry/issues/new?template=bug_report.md
    about: Use this to report a problem with the site, data, or automation
  - name: Feature Request
    url: https://github.com/SteveLLamb/mediastandards-registry/issues/new?template=feature_request.md
    about: Suggest a new capability, enhancement, or improvement
  - name: 💬 General Discussion
    url: https://github.com/SteveLLamb/mediastandards-registry/discussions
    about: For open-ended topics or clarifications