name: Build MSR Site and Test

on:
  workflow_run:
    workflows: ["Build MasterReference Index"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write 

concurrency:
  group: msr-site-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    if: >
      github.event_name != 'workflow_run' || 
      github.event.workflow_run.conclusion == 'success'
    name: Build MSR
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Check upstream PR marker
        id: guard
        if: github.event_name == 'workflow_run'
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            if (!run) { core.setOutput('skip', 'false'); return; }
            const { owner, repo } = context.repo;
            const artifacts = await github.paginate(github.rest.actions.listWorkflowRunArtifacts, {
              owner, repo, run_id: run.id, per_page: 100
            });
            const marker = artifacts.find(a => a.name && a.name.startsWith('skip-site-build-pr-'));
            const prMatch = marker && /^skip-site-build-pr-(\d+)$/.test(marker.name) ? marker.name.match(/^skip-site-build-pr-(\d+)$/)[1] : '';
            const prNum = prMatch || '';
            core.info(`skip-site-build artifact present: ${!!marker}${prNum ? ` (PR #${prNum})` : ''}`);
            core.setOutput('skip', marker ? 'true' : 'false');
            core.setOutput('pr', prNum);

      - name: Skipping site build (upstream PR open)
        if: steps.guard.outputs.skip == 'true'
        run: |
          echo "⏭️  Skipping MSR site build because upstream workflow opened PR #${{ steps.guard.outputs.pr }}."

      - uses: actions/checkout@v4
        if: steps.guard.outputs.skip != 'true'
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        if: steps.guard.outputs.skip != 'true'
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install
        if: steps.guard.outputs.skip != 'true'
        run: npm ci

      - name: Validate registries
        if: steps.guard.outputs.skip != 'true'
        run: npm run validate

      - name: Canonicalize registries (no-op if clean)
        if: steps.guard.outputs.skip != 'true'
        run: |
          npm run canonicalize
          git add src/main/data
          if git diff --cached --quiet; then
            echo "No canonicalization changes."
          else
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m "chore: canonicalize registries"
            git push
          fi

      - name: Build site
        if: steps.guard.outputs.skip != 'true'
        env:
          GH_PAGES_BUILD: true
        run: npm run build

      - name: Generate API stats
        if: steps.guard.outputs.skip != 'true'
        run: |
          mkdir -p build/api
          node src/main/scripts/utils/buildStats.js
          cp tools/apiViewer.html build/api/viewer.html

      - name: Add CNAME for custom domain
        if: steps.guard.outputs.skip != 'true'
        run: echo 'mediastandardsregistry.org' > ./build/CNAME

      - name: Publish to gh-pages
        if: steps.guard.outputs.skip != 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
          # optional hardening:
          # publish_branch: gh-pages
          # force_orphan: true