name: Build MSR Site and Test

on:
  workflow_run:
    workflows: ["Build MasterReference Index"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write 

concurrency:
  group: msr-site-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    if: >
      github.event_name != 'workflow_run' || 
      github.event.workflow_run.conclusion == 'success'
    name: Build MSR
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Validate registries
        run: npm run validate

      - name: Canonicalize registries (no-op if clean)
        run: |
          npm run canonicalize
          git add src/main/data
          if git diff --cached --quiet; then
            echo "No canonicalization changes."
          else
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m "chore: canonicalize registries"
            git push
          fi

      - name: Generate API stats
        run: node src/main/scripts/utils/buildStats.js

      - name: Build site
        env:
          GH_PAGES_BUILD: true
        run: npm run build

      - name: Copy API stats into site
        run: |
          mkdir -p build/api
          cp tools/apiViewer.html build/api/viewer.html

      - name: Add CNAME for custom domain
        run: echo 'mediastandardsregistry.org' > ./build/CNAME

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
          # optional hardening:
          # publish_branch: gh-pages
          # force_orphan: true