name: Extract SMPTE Documents

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios cheerio dayjs

      - name: Run extraction
        run: node src/main/scripts/extractDocs.js > src/main/output/documents.json

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: documents-json
          path: src/main/output/documents.json