name: build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: npm install

    - name: validate registries
      run: npm run validate

    - name: verify that the registries are canonicalized
      if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
      run: |
          npm run canonicalize
          git add src/main/data
          git diff-index --quiet HEAD src/main/data

    - name: commit canonicalized registries
      if: github.ref != 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
          npm run canonicalize
          git add src/main/data
          git config --global user.name 'Steve LLamb'
          git config --global user.email 'steve.llamb@bydeluxe.com'
          git diff-index --quiet HEAD src/main/data || git commit -m "Registries have been canonicalized"
          git push

    - run: npm run build
      env:
         GH_PAGES_BUILD: true
    
    - name: Add CNAME for custom domain
      run: echo 'mediastandardsregistry.org' > ./build/CNAME

    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build