name: PR Build Preview (MSR site)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      # Manual PRs that touch site or templates
      - "src/site/**"
      - "src/main/templates/**"
      - "package.json"
      - "package-lock.json"
      # Extract PRs (bot): include because they change the dataset used by the site
      - "src/main/data/**"
  workflow_run:
    workflows: ["Extract SMPTE Documents"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: pages-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    if: >
      (
        github.event_name == 'pull_request'
        && github.event.pull_request.head.repo.full_name == github.repository
        && !startsWith(github.head_ref, 'gh-pages')
      )
      || (
        github.event_name == 'workflow_run'
        && github.event.workflow_run.conclusion == 'success'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Resolve PR for chore/extract-docs (workflow_run only)
        if: ${{ github.event_name == 'workflow_run' }}
        id: findpr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:chore/extract-docs`
            });
            core.setOutput('number', prs.length ? prs[0].number : '');
      - name: Stop if no open Extract PR
        if: ${{ github.event_name == 'workflow_run' && steps.findpr.outputs.number == '' }}
        run: |
          echo "No open PR found for branch chore/extract-docs — nothing to preview."
          exit 0

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || 'chore/extract-docs' }}

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci

      - name: Canonicalize data (sanity)
        run: npm run canonicalize

      - name: Validate dataset
        run: npm run validate

      - run: npm run build   # produces ./build

      - name: Verify build output exists
        run: |
          if [ ! -d build ]; then
            echo "::error::No build/ output directory found after 'npm run build'.";
            echo "Contents of repo root:";
            ls -la;
            echo "\nLikely build output directories in top 2 levels:";
            find . -maxdepth 2 -type d -name "*dist*" -o -name "*build*" -o -name "*public*";
            exit 1;
          fi

      - name: Deploy PR preview to gh-pages/pr/<PR#>
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: pr/${{ github.event_name == 'pull_request' && github.event.pull_request.number || steps.findpr.outputs.number }}
          keep_files: true

      - name: Comment preview URL on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: msr-preview
          number: ${{ github.event_name == 'pull_request' && github.event.pull_request.number || steps.findpr.outputs.number }}
          message: |
            # Review link
            [MSR Build Preview](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr/${{ github.event_name == 'pull_request' && github.event.pull_request.number || steps.findpr.outputs.number }}/)
            _This link updates on new commits to this PR._