name: Validate Document URLs

permissions:
  contents: write

on:
  schedule:
    - cron: "15 04 * * 4"   # 21:15 PT, Thurs (cron in UTC)
  workflow_dispatch:

jobs:
  validate-urls:
    name: Validate URLs in documents.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run URL validation
        run: npm run validate-url

      - name: Upload validation report (if exists)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: url-validation-report
          path: src/main/reports/url_validate_audit.json
          if-no-files-found: ignore

      - name: Auto-commit audit back to main (if changed)
        if: success() || failure()
        run: |
          set -e
          BR="${{ github.event.repository.default_branch }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/main/reports/url_validate_audit.json || true
          if git diff --cached --quiet; then
            echo "No audit changes to commit.";
            exit 0;
          fi
          git commit -m "chore: url validation audit update"
          git push origin HEAD:"$BR"
          echo "✅ Committed url_validate_audit.json to ${BR}"
