name: Validate Document URLs

on:
  schedule:
    - cron: "15 04 * * 4"   # 21:15 PT, Thurs (cron in UTC)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: validate-urls-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-urls:
    name: Validate URLs in documents.json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run URL validation
        run: npm run validate-url

      - name: Upload validation report (if exists)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: url-validation-report
          path: src/main/reports/url_validate_audit.json
          if-no-files-found: ignore

      - name: Read redirectUndefinedCount from audit
        id: audit
        if: success() || failure()
        run: |
          if [ ! -f src/main/reports/url_validate_audit.json ]; then
            echo "redirect_undefined=0" >> $GITHUB_OUTPUT
            exit 0
          fi
          RU=$(jq -r '.redirectUndefinedCount // 0' src/main/reports/url_validate_audit.json)
          echo "redirect_undefined=$RU" >> $GITHUB_OUTPUT
          echo "redirectUndefinedCount=$RU"

      - name: Auto-commit audit back to main (if changed)
        if: success() || failure()
        run: |
          set -e
          BR="${{ github.event.repository.default_branch }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/main/reports/url_validate_audit.json || true
          if git diff --cached --quiet; then
            echo "No audit changes to commit.";
            exit 0;
          fi
          git commit -m "chore: url validation audit update"
          git push origin HEAD:"$BR"
          echo "✅ Committed url_validate_audit.json to ${BR}"

      - name: Run URL normalizer (apply) for missing resolved*
        if: steps.audit.outputs.redirect_undefined != '0'
        run: |
          node src/main/scripts/url.normalize.js --apply

      - name: Read normalize applied count
        id: norm
        if: steps.audit.outputs.redirect_undefined != '0'
        run: |
          if [ -f src/main/reports/url_validate_normalize.json ]; then
            APPLIED=$(jq -r '.applied // 0' src/main/reports/url_validate_normalize.json)
          else
            APPLIED=0
          fi
          echo "applied=$APPLIED" >> $GITHUB_OUTPUT
          echo "normalizeApplied=$APPLIED"

      - name: Validate documents.json
        if: steps.norm.outputs.applied != '0'
        run: npm run validate

      - name: Canonicalize documents.json
        if: steps.norm.outputs.applied != '0'
        env:
          IS_PR_RUN: true
          PR_LOG_PATH: ${{ runner.temp }}/pr-log.log
        run: npm run canonicalize

      - name: Commit canonicalized documents.json
        if: steps.norm.outputs.applied != '0'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/main/data/documents.json
          if git diff --cached --quiet; then
            echo "No canonicalized changes to commit."
            exit 0
          fi
          git commit -m "Canonicalize documents.json after normalize"

      - name: Create PR for normalized URLs
        if: steps.norm.outputs.applied != '0'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'fix: backfill resolved* from URL validation (missing resolved)'
          title: "Backfill resolved* for ${{ steps.audit.outputs.redirect_undefined }} entries"
          body: |
            This PR backfills resolved* fields for entries missing them based on the URL validation audit.
            - Source: src/main/reports/url_validate_audit.json
            - Script: src/main/scripts/url.normalize.js --apply
            - Detected missing resolved*: ${{ steps.audit.outputs.redirect_undefined }}
            - Applied backfills: ${{ steps.norm.outputs.applied }}
          branch: chore/url-normalize/
          base: ${{ github.event.repository.default_branch }}
          delete-branch: true
          add-paths: |
            src/main/data/documents.json
            src/main/reports/url_validate_normalize.json
